version: "3.8"
services:
    web:
        build: .
        container_name: shopping_web
        ports:
            - "5000:5000"
        environment:
            - EMAIL_USER=${EMAIL_USER}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - SECRET_KEY=${SECRET_KEY}
    db:
        image: postgres:latest
        container_name: shopping_db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}