"""empty message

Revision ID: e94951728e33
Revises: 29a51cdf5fc6
Create Date: 2020-12-13 22:47:23.020750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e94951728e33"
down_revision = "29a51cdf5fc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipe_labels",
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["label_id"], ["label.id"],),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipe.id"],),
        sa.PrimaryKeyConstraint("label_id", "recipe_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe_labels")
    op.drop_table("label")
    # ### end Alembic commands ###
